version: '3.9'

services:
  playlist-generator:
    image: stormimousse/playlist-generator:latest
    container_name: m3u-file-generator

    volumes:
      - /path/to/music/folder1:/music1
      - /path/to/music/folder2:/music2
      - /path/to/music/folder3:/music3
    # - /path/to/music/folderX:/musicX

    environment:
      - SCAN_INTERVAL=3600 # in seconds

    restart: unless-stopped
